[workspace]
resolver = "3"
members = ["crates/*", "apps/*"]

[workspace.package]
version = "0.0.0"
edition = "2024"
rust-version = "1.95"
license = "GPL-3.0-or-later"
publish = false

[workspace.dependencies]
motix-core = { path = "crates/motix-core" }
motix-app = { path = "crates/motix-app" }
motix-ui = { path = "crates/motix-ui" }
eframe = { version = "0.36.2", default-features = false, features = ["wgpu", "accesskit", "default_fonts", "wayland", "x11"] }
egui = "0.36.2"
egui_tiles = "0.17.1"
egui_kittest = { version = "0.36.2", features = ["wgpu", "snapshot"] }
rfd = "0.17.2"

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"
unreachable_pub = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
module_name_repetitions = "allow"

[profile.release]
lto = "thin"
codegen-units = 1
